adapter_mode: dual
af_model_folder: /home/sareeves/software/esm-msr-release/data/tsuboyama/AlphaFold_model_PDBs
batch_size: 256
benchmark_data_path: ./data/preprocessed/
cache_path: ../esm-msr/cache_may22_twostep
calib_delay_steps: 0
calib_lr_mult: 20.0
check_val_every_n_epoch: 1
checkpoint_filename: '{epoch:02d}-{val_rho_combined_avg:.3f}'
checkpoint_path: ./checkpoints
combine_validation: false
comet_api_key: jxbqykQ7uyZi3c02oRlbDLS1q
comet_project_name: esm-msr-april2026
dataloading: cycle
detach_calibration: false
detach_ensemble_input: true
detach_regression: false
double_weight: 1.0
early_stopping_metric: val_rho_combined_avg
early_stopping_patience: 0
experiment_name: msr_dual_ensemble_small_large_r1a4
freeze_mt_adapter: false
freeze_wt_adapter: false
freeze_wt_after_epoch: 1000
freeze_wt_on_convergence: false
gpus: 1
huber_delta: 1.0
incl_doubles: true
incl_mut_ctx: false
incl_reversions: false
incl_sequence_head_mt: true
incl_sequence_head_wt: true
incl_singles: true
incl_structure_encoder_mt: false
incl_structure_encoder_wt: false
invert_list_loss: false
lambda_epi_combined: 0.0
lambda_rank_combined: 1.0
lambda_rank_wt: 1.0
lambda_reg_combined: 1.0
lambda_reg_wt: 1.0
last_n_layers_mt: 0
last_n_layers_wt: 0
learning_rate: 0.0002
load_lora_checkpoint: null
load_wt_only: false
loader_strategy: all
log_dir: ./logs
log_every_n_steps: 25
lora_alpha_mt: 4
lora_alpha_wt: 4
lora_dropout_mt: 0.1
lora_dropout_wt: 0.1
lora_mode: ensemble
lora_rank_mt: 1
lora_rank_wt: 1
lr_total_steps: null
lr_warmup_steps: 500
mask_strategy: null
max_train_proteins: -1
micro_batch_size: 16
model_device: cuda:0
monitor_metric: val_rho_combined_avg
monitor_mode: max
mt_lora_delay_steps: 0
mt_reg_mask: all
mut_ctx_weight: 0.5
mut_structures_root: /home/sareeves/software/esm-msr/data/tsuboyama/FINAL_results/
num_epochs: 20
num_sanity_val_steps: 0
num_workers: 4
offline: false
offline_model: false
precision: bf16-mixed
premask_coords: false
rank_loss: listmle
raw_data_file: /home/sareeves/software/esm-msr-release/data/tsuboyama/Tsuboyama2023_Dataset2_Dataset3_20230416.csv
reg_loss: mse
regenerate_cache: false
remove_spurs_homologs: false
residual_lr_mult: 0.1
residual_wd: 1.0e-05
resume_global_step: 0
reversion_weight: 0.5
save_top_k: 5
score_column: ddG_ML
seed: 1
shared_bias_init: 0.0
shared_scale_init: 0.3
skip_val: false
split_file: /home/sareeves/software/esm-msr-release/data/hyperopt_splits.pkl
strategy: auto
subset_caps:
  double: null
  mut_ctx: 0.0
  reversion: 0.0
  single: null
subset_size: 16
target_mode_mt: expanded
target_mode_wt: expanded
train_dataloader_names:
- cycled_train
unfreeze_layernorms_mt: false
unfreeze_layernorms_wt: false
use_dora_mt: false
use_dora_wt: false
use_plddt: false
val_dataloader_names:
- 1A32
- 1I2T
- 1R69
- 1SF0_V59K
- 1YEZ_V46S
- 1ZHC
- 2CJJ
- 2JT1
- 2JWT
- 2JZ2
- 2KWH
- 2L7F
- 2L7M
- 2L9R
- 2LCL
- 2M0C
- 2MC5
- 2MKY
- 2QFF
- 5Z2S
- HEEH_rd4_0097
- HEEH_rd4_0349
- r11_1081_TrROS_Hall
- v2K43S_2KVV
- v2_2LDM
- v2_4UZX
- ptmuld
- s461
- ssym
version: '1'
weight_decay: 0
wt_convergence_metric: rho_wt
wt_convergence_patience: 1
zero_epistasis_for_singles: true
